modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="mg_economy"
version="1.0.1"
displayName="MG Economy"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Minecrafted Gaming"
description="Basic server economy mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mg_economy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration